"""
Intelligence Response.

Represents a response generated by an intelligence provider.
"""


class IntelligenceResponse:
    """Represent an intelligence response."""

    def __init__(
        self,
        content: str,
        provider: str,
    ) -> None:
        """Initialize the response."""
        self._content = content
        self._provider = provider

    @property
    def content(self) -> str:
        """Return the generated content."""
        return self._content

    @property
    def provider(self) -> str:
        """Return the provider name."""
        return self._provider